import type { Listing, MarketPrice } from '@/types';

// Local images from C:\Users\praveen\Desktop\Flamora\Agri\Images (copied to public/images)
const IMG = (filename: string) => `/images/${encodeURIComponent(filename)}`;

// Map listing title to image filename (for listings without exact match, use closest available)
const IMAGE_MAP: Record<string, string> = {
  'Organic Paddy Rice - Vellore': 'Harvesting Service - Thanjavur.jfif',
  'Fresh Groundnut - Kanchipuram': 'Fresh Groundnut - Coimbatore.jfif',
  'Organic Tomato - Kanchipuram': 'Organic Tomato - Coimbatore.png',
  'Fresh Onion - Villupuram': 'Fresh Onion - Perambalur.avif',
  'Lady Finger - Chengalpattu': 'Lady Finger - Madurai.webp',
  'Fresh Banana Bunch - Thiruvallur': 'Fresh Banana Bunch - Madurai.webp',
  'Mango Alphonso - Krishnagiri': 'Mango Alphonso - Krishnagiri.jpg',
  'Coconut - Chengalpattu': 'Coconut - Pollachi.webp',
  'Jasmine Flowers - Tiruvannamalai': 'Jasmine Flowers - Salem.webp',
  'Marigold - Chennai': 'Marigold - Madurai.jfif',
  'Native Breed Cows - Vellore': 'Native Breed Cows - Erode.jpg',
  'Goat Kids - Tiruvannamalai': 'Goat Kids - Salem.jfif',
  'Buffalo Milk - Vellore': 'Buffalo Milk - Erode.jfif',
  'Fresh Curd - Kanchipuram': 'Fresh Curd - Coimbatore.jpg',
  'Tractor for Rent - Kanchipuram': 'Tractor for Rent - Coimbatore.jfif',
  'Harvester Machine - Vellore': 'Harvester Machine - Thanjavur.jfif',
  'Spray Pump - Tiruvannamalai': 'Spray Pump - Salem.webp',
  'Organic Compost - Kanchipuram': 'Organic Compost - Coimbatore.jfif',
  'NPK Fertilizer - Chennai': 'NPK Fertilizer - Madurai.jfif',
  'Neem Oil Pesticide - Tiruvannamalai': 'Neem Oil Pesticide - Salem.jfif',
  'Cattle Feed Pellets - Kanchipuram': 'Cattle Feed Pellets - Coimbatore.jfif',
  'Hay & Fodder - Vellore': 'Hay & Fodder - Erode.jfif',
  'Tractor Ploughing Service - Kanchipuram': 'Tractor Ploughing Service - Coimbatore.jpg',
  'Crop Spraying Service - Chengalpattu': 'Crop Spraying Service - Madurai.jfif',
  'Harvesting Service - Vellore': 'Harvesting Service - Thanjavur.jfif',
};

const getImageUrl = (title: string) => IMG(IMAGE_MAP[title] || 'Fresh Groundnut - Coimbatore.jfif');

export const MOCK_LISTINGS: Partial<Listing>[] = [
  // Farm Produce
  {
    id: '1',
    title: 'Organic Paddy Rice - Vellore',
    category: { id: '1', name: 'Farm Produce', slug: 'farm-produce' },
    quantity: 5000,
    unit: 'kg',
    price: 28,
    isPriceNegotiable: true,
    location: { district: 'Vellore', village: 'Katpadi' },
    media: [{ url: getImageUrl('Organic Paddy Rice - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 124,
    seller: { name: 'Kumar Farms', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '2',
    title: 'Fresh Groundnut - Kanchipuram',
    category: { id: '1', name: 'Farm Produce', slug: 'farm-produce' },
    quantity: 1000,
    unit: 'kg',
    price: 85,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Uthiramerur' },
    media: [{ url: getImageUrl('Fresh Groundnut - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Murugan', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  // Vegetables
  {
    id: '3',
    title: 'Organic Tomato - Kanchipuram',
    category: { id: '2', name: 'Vegetables', slug: 'vegetables' },
    quantity: 500,
    unit: 'kg',
    price: 28,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Sriperumbudur' },
    media: [{ url: getImageUrl('Organic Tomato - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 124,
    seller: { name: 'Kumar Farms', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '4',
    title: 'Fresh Onion - Villupuram',
    category: { id: '2', name: 'Vegetables', slug: 'vegetables' },
    quantity: 2000,
    unit: 'kg',
    price: 22,
    isPriceNegotiable: false,
    location: { district: 'Villupuram', village: 'Kallakurichi' },
    media: [{ url: getImageUrl('Fresh Onion - Villupuram'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Sellamuthu', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  {
    id: '5',
    title: 'Lady Finger - Chengalpattu',
    category: { id: '2', name: 'Vegetables', slug: 'vegetables' },
    quantity: 300,
    unit: 'kg',
    price: 35,
    isPriceNegotiable: true,
    location: { district: 'Chengalpattu', village: 'Maduranthakam' },
    media: [{ url: getImageUrl('Lady Finger - Chengalpattu'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 67,
    seller: { name: 'Ganesh', avatarUrl: '' },
    createdAt: '2025-02-22T09:00:00Z',
  },
  // Fruits
  {
    id: '6',
    title: 'Fresh Banana Bunch - Thiruvallur',
    category: { id: '3', name: 'Fruits', slug: 'fruits' },
    quantity: 100,
    unit: 'bunch',
    price: 45,
    isPriceNegotiable: false,
    location: { district: 'Thiruvallur', village: 'Ponneri' },
    media: [{ url: getImageUrl('Fresh Banana Bunch - Thiruvallur'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Murugan', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  {
    id: '7',
    title: 'Mango Alphonso - Krishnagiri',
    category: { id: '3', name: 'Fruits', slug: 'fruits' },
    quantity: 500,
    unit: 'kg',
    price: 120,
    isPriceNegotiable: true,
    location: { district: 'Krishnagiri', village: 'Hosur' },
    media: [{ url: getImageUrl('Mango Alphonso - Krishnagiri'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 256,
    seller: { name: 'Lakshmi Farms', avatarUrl: '' },
    createdAt: '2025-02-25T08:00:00Z',
  },
  {
    id: '8',
    title: 'Coconut - Chengalpattu',
    category: { id: '3', name: 'Fruits', slug: 'fruits' },
    quantity: 1000,
    unit: 'piece',
    price: 15,
    isPriceNegotiable: true,
    location: { district: 'Chengalpattu', village: 'Tambaram' },
    media: [{ url: getImageUrl('Coconut - Chengalpattu'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 112,
    seller: { name: 'Karthik', avatarUrl: '' },
    createdAt: '2025-02-21T11:00:00Z',
  },
  // Flowers
  {
    id: '9',
    title: 'Jasmine Flowers - Tiruvannamalai',
    category: { id: '4', name: 'Flowers', slug: 'flowers' },
    quantity: 50,
    unit: 'kg',
    price: 350,
    isPriceNegotiable: true,
    location: { district: 'Tiruvannamalai', village: 'Cheyyar' },
    media: [{ url: getImageUrl('Jasmine Flowers - Tiruvannamalai'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 256,
    seller: { name: 'Lakshmi Florals', avatarUrl: '' },
    createdAt: '2025-02-25T08:00:00Z',
  },
  {
    id: '10',
    title: 'Marigold - Chennai',
    category: { id: '4', name: 'Flowers', slug: 'flowers' },
    quantity: 200,
    unit: 'kg',
    price: 80,
    isPriceNegotiable: true,
    location: { district: 'Chennai', village: 'Ambattur' },
    media: [{ url: getImageUrl('Marigold - Chennai'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Rani Florals', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  // Livestock
  {
    id: '11',
    title: 'Native Breed Cows - Vellore',
    category: { id: '5', name: 'Livestock', slug: 'livestock' },
    quantity: 2,
    unit: 'piece',
    price: 45000,
    isPriceNegotiable: true,
    location: { district: 'Vellore', village: 'Gudiyatham' },
    media: [{ url: getImageUrl('Native Breed Cows - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 189,
    seller: { name: 'Gopal Cattle', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '12',
    title: 'Goat Kids - Tiruvannamalai',
    category: { id: '5', name: 'Livestock', slug: 'livestock' },
    quantity: 5,
    unit: 'piece',
    price: 8000,
    isPriceNegotiable: true,
    location: { district: 'Tiruvannamalai', village: 'Polur' },
    media: [{ url: getImageUrl('Goat Kids - Tiruvannamalai'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 67,
    seller: { name: 'Muthu Livestock', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  // Dairy
  {
    id: '13',
    title: 'Buffalo Milk - Vellore',
    category: { id: '6', name: 'Dairy', slug: 'dairy' },
    quantity: 200,
    unit: 'L',
    price: 55,
    isPriceNegotiable: false,
    location: { district: 'Vellore', village: 'Wallajah' },
    media: [{ url: getImageUrl('Buffalo Milk - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 67,
    seller: { name: 'Gopal Dairy', avatarUrl: '' },
    createdAt: '2025-02-22T09:00:00Z',
  },
  {
    id: '14',
    title: 'Fresh Curd - Kanchipuram',
    category: { id: '6', name: 'Dairy', slug: 'dairy' },
    quantity: 50,
    unit: 'kg',
    price: 80,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Sriperumbudur' },
    media: [{ url: getImageUrl('Fresh Curd - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 45,
    seller: { name: 'Kannan Dairy', avatarUrl: '' },
    createdAt: '2025-02-22T09:00:00Z',
  },
  // Equipment
  {
    id: '15',
    title: 'Tractor for Rent - Kanchipuram',
    category: { id: '7', name: 'Equipment', slug: 'equipment' },
    quantity: 1,
    unit: 'day',
    price: 2500,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Uthiramerur' },
    media: [{ url: getImageUrl('Tractor for Rent - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 156,
    seller: { name: 'Kumar Farms', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '16',
    title: 'Harvester Machine - Vellore',
    category: { id: '7', name: 'Equipment', slug: 'equipment' },
    quantity: 1,
    unit: 'acre',
    price: 3500,
    isPriceNegotiable: true,
    location: { district: 'Vellore', village: 'Katpadi' },
    media: [{ url: getImageUrl('Harvester Machine - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Agri Equipment Co', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  {
    id: '17',
    title: 'Spray Pump - Tiruvannamalai',
    category: { id: '7', name: 'Equipment', slug: 'equipment' },
    quantity: 2,
    unit: 'piece',
    price: 4500,
    isPriceNegotiable: false,
    location: { district: 'Tiruvannamalai', village: 'Chengam' },
    media: [{ url: getImageUrl('Spray Pump - Tiruvannamalai'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 34,
    seller: { name: 'Farm Tools TN', avatarUrl: '' },
    createdAt: '2025-02-21T11:00:00Z',
  },
  // Fertilizers
  {
    id: '18',
    title: 'Organic Compost - Kanchipuram',
    category: { id: '8', name: 'Fertilizers', slug: 'fertilizers' },
    quantity: 500,
    unit: 'kg',
    price: 8,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Kanchipuram' },
    media: [{ url: getImageUrl('Organic Compost - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 234,
    seller: { name: 'Green Earth Organics', avatarUrl: '' },
    createdAt: '2025-02-25T08:00:00Z',
  },
  {
    id: '19',
    title: 'NPK Fertilizer - Chennai',
    category: { id: '8', name: 'Fertilizers', slug: 'fertilizers' },
    quantity: 50,
    unit: 'kg',
    price: 350,
    isPriceNegotiable: false,
    location: { district: 'Chennai', village: 'Avadi' },
    media: [{ url: getImageUrl('NPK Fertilizer - Chennai'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 78,
    seller: { name: 'Agri Inputs', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '20',
    title: 'Neem Oil Pesticide - Tiruvannamalai',
    category: { id: '8', name: 'Fertilizers', slug: 'fertilizers' },
    quantity: 5,
    unit: 'L',
    price: 450,
    isPriceNegotiable: true,
    location: { district: 'Tiruvannamalai', village: 'Arani' },
    media: [{ url: getImageUrl('Neem Oil Pesticide - Tiruvannamalai'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 56,
    seller: { name: 'Organic Solutions', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  // Cattle Feed
  {
    id: '21',
    title: 'Cattle Feed Pellets - Kanchipuram',
    category: { id: '9', name: 'Cattle Feed', slug: 'cattle-feed' },
    quantity: 500,
    unit: 'kg',
    price: 28,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Sriperumbudur' },
    media: [{ url: getImageUrl('Cattle Feed Pellets - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Gopal Dairy', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '22',
    title: 'Hay & Fodder - Vellore',
    category: { id: '9', name: 'Cattle Feed', slug: 'cattle-feed' },
    quantity: 1000,
    unit: 'kg',
    price: 12,
    isPriceNegotiable: true,
    location: { district: 'Vellore', village: 'Ranipet' },
    media: [{ url: getImageUrl('Hay & Fodder - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 67,
    seller: { name: 'Muthu Livestock', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  // Services
  {
    id: '23',
    title: 'Tractor Ploughing Service - Kanchipuram',
    category: { id: '10', name: 'Services', slug: 'services' },
    quantity: 1,
    unit: 'acre',
    price: 3500,
    isPriceNegotiable: true,
    location: { district: 'Kanchipuram', village: 'Uthiramerur' },
    media: [{ url: getImageUrl('Tractor Ploughing Service - Kanchipuram'), type: 'image' }],
    status: 'active',
    isFeatured: true,
    viewCount: 156,
    seller: { name: 'Kumar Farms', avatarUrl: '' },
    createdAt: '2025-02-24T10:00:00Z',
  },
  {
    id: '24',
    title: 'Crop Spraying Service - Chengalpattu',
    category: { id: '10', name: 'Services', slug: 'services' },
    quantity: 1,
    unit: 'acre',
    price: 1200,
    isPriceNegotiable: true,
    location: { district: 'Chengalpattu', village: 'Tambaram' },
    media: [{ url: getImageUrl('Crop Spraying Service - Chengalpattu'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 89,
    seller: { name: 'Agri Spray Services', avatarUrl: '' },
    createdAt: '2025-02-23T14:00:00Z',
  },
  {
    id: '25',
    title: 'Harvesting Service - Vellore',
    category: { id: '10', name: 'Services', slug: 'services' },
    quantity: 1,
    unit: 'acre',
    price: 4000,
    isPriceNegotiable: true,
    location: { district: 'Vellore', village: 'Katpadi' },
    media: [{ url: getImageUrl('Harvesting Service - Vellore'), type: 'image' }],
    status: 'active',
    isFeatured: false,
    viewCount: 112,
    seller: { name: 'Paddy Harvest Co', avatarUrl: '' },
    createdAt: '2025-02-22T09:00:00Z',
  },
];

export const CATEGORY_NAMES: Record<string, string> = {
  'farm-produce': 'Farm Produce',
  vegetables: 'Vegetables',
  fruits: 'Fruits',
  flowers: 'Flowers',
  livestock: 'Livestock',
  dairy: 'Dairy',
  equipment: 'Equipment',
  fertilizers: 'Fertilizers',
  'cattle-feed': 'Cattle Feed',
  services: 'Services',
};

export const MOCK_MARKET_PRICES: Partial<MarketPrice>[] = [
  { cropName: 'Tomato', cropNameTa: 'தக்காளி', minPrice: 22, maxPrice: 35, modalPrice: 28, unit: 'kg', trend: 'up' },
  { cropName: 'Onion', cropNameTa: 'வெங்காயம்', minPrice: 18, maxPrice: 28, modalPrice: 23, unit: 'kg', trend: 'down' },
  { cropName: 'Potato', cropNameTa: 'உருளைக்கிழங்கு', minPrice: 15, maxPrice: 22, modalPrice: 18, unit: 'kg', trend: 'stable' },
];
